#Actividad 12
frutas = ["fresa", "mango", "durazno"]
frutas.append("platano")
print(frutas) 
frutas.insert(1, "uva")
print(frutas)
frutas.remove("platano")
print(frutas) 
fruta_eliminada = frutas.pop(2)
print(frutas)
print(fruta_eliminada) 
frutas.sort()
print(frutas) 
frutas.reverse()
print(frutas)